language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
  - 7.0
  - 7.1

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit

after_script:

after_failure:
